# Generated by Django 5.1.1 on 2024-11-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descripcion',
        ),
    ]
