# Generated by Django 5.1.1 on 2024-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_categoria_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cantidad_disponible',
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
