# Generated by Django 5.1.1 on 2024-12-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_eliminado_and_more'),
        ('api', '0008_product_codigo'),
    ]

    operations = [
    ]
