# Generated by Django 5.1.1 on 2024-12-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20241202_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientostock',
            old_name='cantidad',
            new_name='cantida_disponible',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cantidad_disponible',
            new_name='cantida_disponible_disponible',
        ),
    ]
