# Generated by Django 5.1.1 on 2024-12-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_cantida_disponible_disponible_product_cantida_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientostock',
            old_name='cantida_disponible',
            new_name='cantidad_disponible',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cantida_disponible',
            new_name='cantidad_disponible',
        ),
    ]
