# Generated by Django 5.1.1 on 2024-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('modificacion', 'Modificacion'), ('eliminacion', 'Eliminacion'), ('salida', 'Salida')], max_length=20),
        ),
    ]
