# Generated by Django 5.1.1 on 2024-12-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_cantida_disponible_movimientostock_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='eliminado',
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
    ]
