# Generated by Django 5.1.1 on 2024-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_movimientostock_cantidad_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
